version: '3.7'
services:
  api:
    build:
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - 4000:4000
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
      - 35729:35729
    depends_on:
      - api
  db:
    image: mongo
    ports:
    - 27017:27017
    volumes:
    - ./data:/data/db