FROM node:10.16.0

ADD package-lock.json /pacage-lock.json
ADD package.json /package.json

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
RUN npm install

WORKDIR /app
ADD . /app

EXPOSE 4000

CMD ["npm", "start"]